const APP_VERSION='0.15.6'; const APP_DATE='19.09.2026';
const SUPABASE_URL='https://pgjhswuduxrbktjzdnty.supabase.co';
const SUPABASE_KEY='sb_publishable_MKZLIuSWTfWSs_o5ABLT0Q_hqaWlMb5';
const STATE_ID='00000000-0000-0000-0000-000000000001';
const KEY='wildverteilung_v4';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const seed={users:[],kills:[],hunts:[],groups:[],session:null};
let db=structuredClone(seed);
let authUser=null;
let syncTimer=null;
function localCandidate(){
  for(const k of [KEY,'wildverteilung_v3','wildverteilung_v2','wildverteilung_v1']){
    try{const x=JSON.parse(localStorage.getItem(k)||'null'); if(x&&Array.isArray(x.users)) return x}catch(e){}
  }
  return null;
}
function normalizeDb(x){
  x=x||structuredClone(seed); x.users=x.users||[]; x.kills=x.kills||[]; x.hunts=x.hunts||[]; x.groups=x.groups||[];
  x.users.forEach(u=>{u.groups=Array.isArray(u.groups)?u.groups:[];u.active=u.active!==false;if(!u.status)u.status=u.fixedHunter?'fixed':'guest';u.isHunter=true;u.fixedHunter=u.status==='fixed'||u.status==='tenant';u.isDistributor=u.status==='tenant';u.isAdmin=u.status==='tenant';if((u.name||'').trim().toLowerCase()==='benjamin böttcher'){u.mainAdmin=true;u.status='admin';u.isDistributor=true;u.isAdmin=true}});
  x.kills.forEach(k=>(k.parts||[]).forEach(p=>p.rejectedBy=p.rejectedBy||[])); x.hunts.forEach(h=>(h.allocations||[]).forEach(a=>a.rejectedBy=a.rejectedBy||[]));
  return x;
}
function stablePersonLocalId(uuid){
  let h=2166136261;
  for(const c of String(uuid||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}
  return -(Math.abs(h>>>0)+1);
}
function personStatusFromDb(status,mainAdmin=false){return mainAdmin?'admin':status==='paechter'?'tenant':status==='fest'?'fixed':'guest'}
async function syncPersonsFromSupabase(){
  const {data:rows,error}=await sb.from('personen').select('id,vorname,nachname,status,aktiv,hauptadministrator,auth_user_id');
  if(error) throw error;
  for(const r of (rows||[])){
    const name=[r.vorname,r.nachname].filter(Boolean).join(' ').trim();
    let u=db.users.find(x=>x.sourcePersonId===r.id)
      ||(r.auth_user_id?db.users.find(x=>x.authUserId===r.auth_user_id):null)
      ||db.users.find(x=>(x.name||'').trim().toLowerCase()===name.toLowerCase());
    if(!u){u={id:stablePersonLocalId(r.id),groups:[]};db.users.push(u)}
    u.sourcePersonId=r.id;
    u.name=name||u.name||'Unbenannt';
    u.status=personStatusFromDb(r.status,!!r.hauptadministrator);
    u.active=r.aktiv!==false;
    u.mainAdmin=!!r.hauptadministrator;
    u.authUserId=r.auth_user_id||null;
    u.groups=Array.isArray(u.groups)?u.groups:[];
    u.fixedHunter=u.status==='fixed'||u.status==='tenant';
    u.isHunter=true;
    u.isDistributor=u.status==='tenant'||u.status==='admin';
    u.isAdmin=u.status==='tenant'||u.status==='admin';
  }
}
async function loadCloudState(){
  const {data,error}=await sb.from('app_state').select('daten').eq('id',STATE_ID).maybeSingle();
  if(error) throw error;
  if(data?.daten) db=normalizeDb(data.daten);
  else {
    const old=localCandidate();
    db=normalizeDb(old||seed);
  }
  // Personen/Pächter werden bei jedem Start aus der dauerhaften Supabase-Tabelle ergänzt/aktualisiert.
  // Ein App-Update kann dadurch keine bereits vorhandenen Pächter mehr verschwinden lassen.
  await syncPersonsFromSupabase();
  await saveNow();
}
async function saveNow(){
  if(!authUser)return;
  const clean=JSON.parse(JSON.stringify({...db,session:null}));
  const {error}=await sb.from('app_state').upsert({id:STATE_ID,daten:clean,geaendert_am:new Date().toISOString()});
  if(error){console.error(error);alert('Synchronisierung fehlgeschlagen: '+error.message)}
}
function save(){clearTimeout(syncTimer);syncTimer=setTimeout(saveNow,120)}
function bindSessionPerson(){
  if(!authUser)return false;
  let u=db.users.find(x=>x.authUserId===authUser.id);
  // Einmalige Zuordnung des bereits vorhandenen Hauptadministrators aus V0.14.0.
  if(!u){
    const main=db.users.find(x=>x.mainAdmin);
    if(main && !main.authUserId){main.authUserId=authUser.id;u=main;save()}
  }
  if(!u || !u.active || (u.status!=='tenant'&&u.status!=='admin')){
    db.session=null;
    return false;
  }
  db.session=u.id;
  return true;
}
const A=document.querySelector('#app');
function confirmSaved(msg='Gespeichert'){alert('✓ '+msg);}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shell(x){A.innerHTML=`<div class='wrap'>${x}</div>`} function user(){return db.users.find(x=>x.id===db.session)} function hunters(){return db.users.filter(x=>x.active&&!x.deleted)} function fixedHunters(){return db.users.filter(x=>x.active&&!x.deleted&&!x.temporary&&(x.status==='fixed'||x.status==='tenant'||x.fixedHunter))} function canDistribute(){let u=user();return !!(u&&(u.isDistributor||u.isAdmin))} function isAdmin(){return !!user()?.isAdmin}
function login(){shell(`<div class='brand'><div class='mark'>🦌</div><h1>Wildverteilung</h1><div class='small'>Jagdgemeinschaft</div></div><div class='card'><label>E-Mail</label><input id='l' type='email' autocomplete='username' placeholder='E-Mail des Pächter-Zugangs'><label>Passwort</label><input id='p' type='password' autocomplete='current-password'><button class='btn' id='go'>Anmelden</button><div class='small' style='margin-top:12px'>Nur Pächter haben Zugang. Anmeldung läuft zentral über Supabase Auth.</div></div><p class='small' style='text-align:center'><b>Version ${APP_VERSION}</b> · Stand ${APP_DATE}</p>`);go.onclick=async()=>{go.disabled=true;go.textContent='Anmeldung …';const {data,error}=await sb.auth.signInWithPassword({email:l.value.trim(),password:p.value});if(error){go.disabled=false;go.textContent='Anmelden';return alert('Anmeldung fehlgeschlagen: '+error.message)}authUser=data.user;try{await loadCloudState();if(!bindSessionPerson()){await sb.auth.signOut();authUser=null;alert('Dieser Zugang ist keinem aktiven Pächter zugeordnet.');return login()}home()}catch(e){await sb.auth.signOut();authUser=null;alert('Datenbank konnte nicht geladen werden. Bitte zuerst die SQL-Datei V0.14 ausführen.\n\n'+e.message);login()}}}
function head(title){return `<div class='top'><button onclick='home()'>‹</button><h2>${title}</h2><button onclick='logout()'>⎋</button></div>`}
window.logout=async()=>{await saveNow();await sb.auth.signOut();authUser=null;db=structuredClone(seed);login()};
function home(){let u=user();if(!u)return login();let manage=canDistribute();shell(`<div class='top'><div><div class='small'>Angemeldet als</div><h2 style='margin:2px 0'>${esc(u.name)}</h2><div class='small'>${u.mainAdmin?'ADMIN · volle Rechte':'Pächter · Verwaltung'}</div></div><button onclick='logout()'>⎋</button></div><div class='grid'><button class='tile' onclick='myShares()'><span>🥩</span>Meine Zuteilungen</button>${manage?`<button class='tile secondary' onclick='newKill()'><span>🦌</span>Schalenwild</button><button class='tile secondary' onclick='drive()'><span>🌿</span>Treibjagd</button><button class='tile' onclick='distribute()'><span>⚖️</span>Offene Verteilung</button><button class='tile secondary' onclick='historyView()'><span>📜</span>Historie</button>`:(u.isHunter?`<button class='tile secondary' onclick='myDrive()'><span>🌿</span>Treibjagd</button>`:'')}${u.isAdmin?`<button class='tile' onclick='hunterAdmin()'><span>👥</span>Personen</button>`:''}</div><div class='small' style='text-align:center;margin-top:20px'>Wildverteilung · <b>Version ${APP_VERSION}</b> · Stand ${APP_DATE}</div>`)} window.home=home;
window.newKill=()=>{shell(`${head('Schalenwild eintragen')}<div class='card'><label>Datum</label><input id='date' type='date' value='${new Date().toISOString().slice(0,10)}'><label>Wildart</label><select id='species'><option>Damwild</option><option>Schwarzwild</option></select><label>Schütze</label><select id='shooter'>${hunters().map(x=>`<option value='${x.id}'>${esc(x.name)}</option>`)}</select><label>Verwertbare Teile</label><div id='checks'>${['Keule links','Keule rechts','Rücken','Vorderviertel links','Vorderviertel rechts'].map((x,i)=>`<label class='item'><input type='checkbox' class='part' value='${x}' ${i<5?'checked':''}> ${x}</label>`).join('')}</div><label>Bemerkung</label><input id='note'><button class='btn' id='savekill'>Stück speichern</button></div>`);let saving=false;savekill.onclick=()=>{if(saving)return;let ps=[...document.querySelectorAll('.part:checked')].map((e,i)=>({id:i,name:e.value,recipient:null,source:'open'}));if(!ps.length)return alert('Mindestens einen verwertbaren Teil auswählen.');saving=true;savekill.disabled=true;savekill.textContent='Wird gespeichert …';let id=Date.now();while(db.kills.some(k=>k.id===id))id++;db.kills.push({id,date:date.value,species:species.value,shooter:+shooter.value,parts:ps,note:note.value,createdBy:user().id});saveNow().then(()=>{confirmSaved('Stück wurde einmalig angelegt. Weiter zur Verteilung.');distribute()}).catch(e=>{saving=false;savekill.disabled=false;savekill.textContent='Stück speichern';alert('Speichern fehlgeschlagen: '+e.message)})}}
window.hunterAdmin=()=>{if(!isAdmin())return home();let gf=window._groupFilter||'all';let active=db.users.filter(u=>u.active&&!u.temporary&&!u.deleted&&(gf==='all'||(u.groups||[]).includes(+gf)));let sections=[['admin','Admin'],['tenant','Pächter'],['fixed','Feste Jäger'],['guest','Nicht feste Jäger']];shell(`${head('Personen')}<div class='card personhero'><div><h3 style='margin:0'>Personenverwaltung</h3><div class='small'>${db.users.filter(u=>u.active&&!u.temporary&&!u.deleted).length} aktive Personen · ${db.groups.length} Gruppen</div></div><button class='btn compact' onclick='personTypeChooser()'>＋ Person</button></div>${db.groups.length?`<div class='card'><label>Gruppe anzeigen</label><select onchange='setGroupFilter(this.value)'><option value='all'>Alle Gruppen</option>${db.groups.map(g=>`<option value='${g.id}' ${String(gf)===String(g.id)?'selected':''}>${esc(g.name)}</option>`).join('')}</select></div>`:''}<div class='personsections'>${sections.map(([st,title])=>{let people=active.filter(u=>u.status===st);return `<section class='personsection'><div class='personsectionhead'><h3>${title}</h3><span>${people.length}</span></div><div class='personlist'>${people.map(u=>personCard(u)).join('')||`<div class='emptygroup'>Keine Personen</div>`}</div></section>`}).join('')}</div><div class='card'><button class='btn secondary' onclick='groupAdmin()'>👥 Gruppen verwalten</button><button class='btn secondary' onclick='showInactive()'>Deaktivierte Personen (${db.users.filter(u=>!u.active).length})</button></div>`) };
function personMatches(u,f,gf){return (f==='all'||u.status===f)&&(gf==='all'||(u.groups||[]).includes(+gf))}
window.setPersonFilter=f=>{window._personFilter=f;hunterAdmin()}; window.setGroupFilter=g=>{window._groupFilter=g;hunterAdmin()};
function statusName(u){return u.status==='admin'?'Admin':u.status==='tenant'?'Pächter':u.status==='fixed'?'Fester Jäger':'Nicht fester Jäger'}
function statusClass(u){return u.status==='admin'?'admin':u.status==='tenant'?'tenant':u.status==='fixed'?'fixed':'guest'}
function personCard(u){let gs=(u.groups||[]).map(id=>db.groups.find(g=>g.id===id)?.name).filter(Boolean);return `<div class='card personcard'><div class='personcardtop'><div><h3>${esc(u.name)}</h3><span class='rolebadge ${statusClass(u)}'>${statusName(u).toUpperCase()}</span>${u.mainAdmin?`<span class='rolebadge admin'>VOLLE RECHTE</span>`:''}</div><button class='editbtn' onclick='personForm(${u.id})'>Bearbeiten ›</button></div><div class='facts'>${u.status!=='guest'?`<span>✓ Schalenwildverteilung</span>`:`<span>Schütze / Jagdteilnehmer</span>`}${u.status==='tenant'?`<span>✓ App-Zugang</span>`:`<span>Kein App-Zugang</span>`}</div>${gs.length?`<div class='grouptags'>${gs.map(g=>`<span>${esc(g)}</span>`).join('')}</div>`:''}</div>`}
window.personTypeChooser=()=>{shell(`${head('Person hinzufügen')}<div class='card'><div class='step'>Schritt 1 · Funktion im Revier</div><h3>Welche Person möchtest du anlegen?</h3><button class='typechoice' onclick='personForm(0,"tenant")'><b>Pächter</b><span>App-Zugang · Verwaltung · Schalenwildverteilung</span></button><button class='typechoice' onclick='personForm(0,"fixed")'><b>Fester Jäger</b><span>Schalenwildverteilung · kein App-Zugang</span></button><button class='typechoice' onclick='personForm(0,"guest")'><b>Nicht fester Jäger</b><span>Als Schütze und Jagdteilnehmer · keine reguläre Schalenwildverteilung</span></button></div>`)};
window.personForm=(id,preset)=>{if(!isAdmin())return;let u=id?db.users.find(x=>x.id===id):null;let st=preset||u?.status||'guest';shell(`${head(u?'Person bearbeiten':'Person anlegen')}<div class='card'><div class='step'>${u?'Personendaten':'Schritt 2 · Personendaten'}</div><div class='rolepreview ${st}'>${st==='tenant'?'PÄCHTER':st==='fixed'?'FESTER JÄGER':'NICHT FESTER JÄGER'}</div><label>Vor- und Nachname</label><input id='pn' value='${esc(u?.name||'')}' placeholder='z. B. Max Mustermann'><label>Telefonnummer <span class='small'>(optional)</span></label><input id='pphone' value='${esc(u?.phone||'')}' placeholder='z. B. 0171 ...'><input type='hidden' id='pstatus' value='${st}'><div class='sectiontitle'><b>Gruppen</b><div class='small'>Eine Person kann mehreren Gruppen angehören.</div></div><div class='groupchecks'>${db.groups.length?db.groups.map(g=>`<label><input type='checkbox' class='pgroup' value='${g.id}' ${(u?.groups||[]).includes(g.id)?'checked':''}> ${esc(g.name)}</label>`).join(''):`<div class='small'>Noch keine Gruppen angelegt. Diese kannst du später zuordnen.</div>`}</div><div id='accessbox' class='sectiontitle'></div><button class='btn' onclick='savePerson(${u?.id||0})'>${u?'Änderungen speichern':'Person anlegen'}</button>${u?`<button class='btn secondary' onclick='changePersonStatus(${u.id})'>Status ändern</button><button class='btn secondary' onclick='toggleUser(${u.id})'>${u.active?'Person deaktivieren':'Person aktivieren'}</button>${!u.mainAdmin?`<button class='btn secondary danger' onclick='deletePerson(${u.id})'>Person löschen</button>`:''}`:''}</div>`);window._editPerson=u;accessFields()};
window.changePersonStatus=id=>{let u=db.users.find(x=>x.id===id);if(u?.mainAdmin)return alert('Der Admin-Status kann nicht in einen Jägerstatus geändert werden.');let n=prompt('Status wählen:\n1 = Pächter\n2 = Fester Jäger\n3 = Nicht fester Jäger');let st=n==='1'?'tenant':n==='2'?'fixed':n==='3'?'guest':null;if(!st)return;u.status=st;u.fixedHunter=st!=='guest';u.isDistributor=st==='tenant';u.isAdmin=st==='tenant';if(st!=='tenant'){u.login='';u.pin=''}save();personForm(id)};
window.accessFields=()=>{let st=document.getElementById('pstatus')?.value,b=document.getElementById('accessbox'),u=window._editPerson;if(!b)return;if(st!=='tenant'){b.innerHTML=`<b>App-Zugang</b><div class='small' style='margin-top:6px'>Diese Person benötigt keine Zugangsdaten.</div>`;return}if(u){b.innerHTML=`<b>App-Zugang</b><div class='small' style='margin-top:6px'>${u.authUserId?'✓ Supabase-Zugang ist verbunden.':'Noch kein Supabase-Zugang verbunden.'}</div>`;return}b.innerHTML=`<b>App-Zugang für Pächter</b><div class='small' style='margin:6px 0 10px'>Der Zugang wird sicher über Supabase angelegt.</div><label>E-Mail-Adresse</label><input id='pemail' type='email' autocomplete='off' placeholder='name@beispiel.de'><label>Startpasswort</label><input id='ppassword' type='password' autocomplete='new-password' placeholder='mindestens 8 Zeichen'>`};
window.savePerson=async(id)=>{let name=pn.value.trim(),st=document.getElementById('pstatus').value;if(!name)return alert('Bitte Vor- und Nachname eingeben.');let u=id?db.users.find(x=>x.id===id):{id:Date.now(),active:true};if(u?.mainAdmin)return alert('Der Admin wird nicht über die Jägerstatus-Felder geändert.');if(!id&&st==='tenant'){if(!user()?.mainAdmin)return alert('Nur der Hauptadministrator darf neue Pächter-Zugänge anlegen.');let email=(document.getElementById('pemail')?.value||'').trim().toLowerCase(),passwort=document.getElementById('ppassword')?.value||'';if(!email||!email.includes('@'))return alert('Bitte eine gültige E-Mail-Adresse eingeben.');if(passwort.length<8)return alert('Das Startpasswort muss mindestens 8 Zeichen haben.');let parts=name.split(/\s+/),vorname=parts.shift()||'',nachname=parts.join(' ');if(!nachname)return alert('Bitte Vor- und Nachname eingeben.');let btn=document.querySelector('button[onclick^=\'savePerson\']');if(btn){btn.disabled=true;btn.textContent='Zugang wird angelegt …'};const {data,error}=await sb.functions.invoke('paechter-verwalten',{body:{vorname,nachname,email,passwort}});if(error||!data?.ok){if(btn){btn.disabled=false;btn.textContent='Person anlegen'}return alert('Pächter konnte nicht angelegt werden: '+(data?.error||error?.message||'Unbekannter Fehler'))}u.sourcePersonId=data.person.id;u.authUserId=data.person.auth_user_id;u.email=email}u.name=name;u.phone=pphone.value.trim();u.status=st;u.groups=[...document.querySelectorAll('.pgroup:checked')].map(x=>+x.value);u.fixedHunter=st==='fixed'||st==='tenant';u.isHunter=true;u.isDistributor=st==='tenant';u.isAdmin=st==='tenant';if(!id)db.users.push(u);await saveNow();confirmSaved(id?'Person wurde aktualisiert.':'Person und App-Zugang wurden angelegt.');hunterAdmin()};
function canDeletePerson(id){return !db.kills.some(k=>k.shooter===id||k.parts.some(p=>p.recipient===id))&&!db.hunts.some(h=>(h.participants||[]).includes(id)||(h.allocations||[]).some(a=>a.recipient===id))}

window.toggleUser=id=>{if(!isAdmin())return;let u=db.users.find(x=>x.id===id);if(u?.mainAdmin)return alert('Der Hauptadministrator kann nicht deaktiviert werden.');u.active=!u.active;save();confirmSaved(u.active?'Person wurde aktiviert.':'Person wurde deaktiviert.');hunterAdmin()};
window.showInactive=()=>{shell(`${head('Deaktivierte Personen')}<div class='personlist'>${db.users.filter(u=>!u.active&&!u.temporary&&!u.deleted).map(u=>personCard(u)).join('')||`<div class='card'>Keine deaktivierten Personen.</div>`}</div>`) };
window.groupAdmin=()=>{shell(`${head('Gruppen')}<div class='card'><h3>Gruppen verwalten</h3><div class='row'><input id='newgroup' placeholder='z. B. Markendorf'><button class='btn compact' onclick='addGroup()'>＋</button></div></div><div class='card'>${db.groups.map(g=>`<div class='item groupadminrow'><div><b>${esc(g.name)}</b><div class='small'>${db.users.filter(u=>(u.groups||[]).includes(g.id)).length} Personen</div></div><button class='editbtn' onclick='deleteGroup(${g.id})'>Löschen</button></div>`).join('')||'<div class="small">Noch keine Gruppen.</div>'}</div>`) };
window.addGroup=()=>{let n=newgroup.value.trim();if(!n)return;if(db.groups.some(g=>g.name.toLowerCase()===n.toLowerCase()))return alert('Diese Gruppe gibt es bereits.');db.groups.push({id:Date.now(),name:n});save();confirmSaved('Gruppe wurde angelegt.');groupAdmin()};
window.deleteGroup=id=>{let g=db.groups.find(x=>x.id===id);if(!confirm(`Gruppe „${g.name}“ löschen? Personen bleiben erhalten.`))return;db.groups=db.groups.filter(x=>x.id!==id);db.users.forEach(u=>u.groups=(u.groups||[]).filter(x=>x!==id));save();groupAdmin()};
function partBase(n){return n.startsWith('Keule')?'Keule':n.startsWith('Vorderviertel')?'Vorderviertel':n}
// Schützenrecht ist eine Sonderzuteilung und verändert die reguläre Reihenfolge nicht.
function regularPartsFor(uid){let out=[];db.kills.forEach(k=>k.parts.forEach(p=>{if(p.recipient===uid && !String(p.source||'').startsWith('Schützen')) out.push({k,p});}));return out}
function lastRegularPart(uid){let rows=regularPartsFor(uid).filter(x=>x.p.accepted!==false).sort((a,b)=>{let d=(b.k.date||'').localeCompare(a.k.date||'');return d||((b.k.id||0)-(a.k.id||0))});return rows[0]?partBase(rows[0].p.name):null}
function score(uid,name,species){let total=0,same=0,kind=0,last=0;regularPartsFor(uid).forEach(({k,p})=>{if(p.accepted===false)return;total++;if(k.species===species)same++;if(partBase(p.name)===partBase(name))kind++;last=Math.max(last,new Date(k.date).getTime()||0)});return kind*8+same*2+total+(last?last/1e15:0)}
function shooterPickHtml(k){let shooter=db.users.find(u=>u.id===k.shooter),open=k.parts.filter(p=>!p.recipient);return `<div class='card'><b>${k.species}</b> · ${k.date}<div class='small'>Schütze: ${esc(shooter?.name)}</div><h3>1. Schütze wählt zuerst</h3><div class='small'>Das Schützenrecht ist eine Sonderzuteilung. Die normale Verteilungsposition bleibt erhalten. Nimmt der Schütze einen Teil, erhält er aus diesem Stück keinen zweiten Anteil.</div>${open.map(p=>`<button class='btn secondary' onclick='pickShooter(${k.id},${p.id})'>${esc(p.name)} an ${esc(shooter?.name)}</button>`).join('')}<button class='link' onclick='shooterWaive(${k.id})'>Schütze verzichtet</button><button class='link' onclick='takeWhole(${k.id})'>Schütze übernimmt das ganze Stück</button></div>`}
window.distribute=()=>{if(!canDistribute())return home();let open=db.kills.filter(k=>k.parts.some(p=>!p.recipient||p.accepted===false));shell(`${head('Offene Verteilung')}${open.length?'':`<div class='card'>Keine offenen Stücke.</div>`}${open.map(k=>{if(!k.shooterDecision)return shooterPickHtml(k);return `<div class='card'><b>${k.species}</b> · ${k.date}<div class='small'>Schütze: ${esc(db.users.find(u=>u.id===k.shooter)?.name)}</div>${k.parts.map(p=>`<div class='item'>${esc(p.name)}: <b>${p.recipient?esc(db.users.find(u=>u.id===p.recipient)?.name):'offen'}</b><div class='small'>${esc(p.source||'')}</div><button class='link danger' onclick='deleteKillPart(${k.id},${p.id})'>Teil löschen</button>${p.recipient&&p.accepted===false&&!String(p.source||'').startsWith('Schützen')?`<div class='row'><button class='btn compact' onclick='adminAcceptPart(${k.id},${p.id})'>Verteilen</button><button class='btn secondary compact' onclick='adminRejectPart(${k.id},${p.id})'>Ablehnen</button></div>`:''}</div>`).join('')}<button class='btn' onclick='auto(${k.id})'>Rest fair verteilen</button><button class='btn secondary danger' onclick='deleteKill(${k.id})'>Schalenwild vollständig löschen</button></div>`}).join('')}`)};
window.pickShooter=(kid,pid)=>{let k=db.kills.find(x=>x.id===kid),p=k.parts.find(x=>x.id===pid);p.recipient=k.shooter;p.source='Schützenrecht – Sonderzuteilung';p.accepted=true;k.shooterDecision='part';save();confirmSaved('Schützenanteil gespeichert. Die normale Verteilungsposition bleibt unverändert.');distribute()};
window.shooterWaive=kid=>{db.kills.find(x=>x.id===kid).shooterDecision='waive';save();confirmSaved('Schütze hat auf das Schützenrecht verzichtet.');distribute()};
window.takeWhole=kid=>{let k=db.kills.find(x=>x.id===kid);k.parts.forEach(p=>{p.recipient=k.shooter;p.source='Schützenrecht – ganzes Stück';p.accepted=true});k.shooterDecision='whole';save();confirmSaved('Ganzes Stück dem Schützen zugeordnet. Die normale Verteilungsposition bleibt unverändert.');distribute()};
function candidateFor(k,p){let hs=fixedHunters();let already=new Set(k.parts.filter(x=>x.recipient).map(x=>x.recipient));p.rejectedBy=p.rejectedBy||[];let candidates=hs.filter(u=>!already.has(u.id)&&!p.rejectedBy.includes(u.id));if(!candidates.length)return null;let wanted=partBase(p.name);let noRepeat=candidates.filter(u=>lastRegularPart(u.id)!==wanted);let pool=noRepeat.length?noRepeat:candidates;return [...pool].sort((a,b)=>score(a.id,p.name,k.species)-score(b.id,p.name,k.species))[0]||null}
window.auto=id=>{let k=db.kills.find(x=>x.id===id);k.parts.forEach(p=>{if(p.recipient)return;let r=candidateFor(k,p);p.recipient=r?.id||null;p.source=r?(lastRegularPart(r.id)===partBase(p.name)?'Vorschlag – gleiche Teile nur mangels Alternative':'Vorschlag – faire Rotation'):'keine berechtigte Person verfügbar';p.accepted=false});save();confirmSaved('Verteilungsvorschlag erstellt. Der Bediener kann jetzt verteilen oder ablehnen.');distribute()};
window.adminAcceptPart=(kid,pid)=>{if(!canDistribute())return;let k=db.kills.find(x=>x.id===kid),p=k?.parts.find(x=>x.id===pid);if(!p||!p.recipient)return;p.accepted=true;p.source=String(p.source||'Zuteilung').replace(/^Vorschlag – /,'Verteilt – ');save();confirmSaved('Zuteilung ist verteilt.');distribute()};
window.adminRejectPart=(kid,pid)=>{if(!canDistribute())return;let k=db.kills.find(x=>x.id===kid),p=k?.parts.find(x=>x.id===pid);if(!p||!p.recipient)return;p.rejectedBy=p.rejectedBy||[];if(!p.rejectedBy.includes(p.recipient))p.rejectedBy.push(p.recipient);p.recipient=null;p.accepted=false;p.source='abgelehnt – neu zu verteilen';let r=candidateFor(k,p);if(r){p.recipient=r.id;p.accepted=false;p.source='nach Ablehnung neu vorgeschlagen';}save();confirmSaved(r?'Ablehnung gespeichert. Nächster Empfänger wurde vorgeschlagen.':'Ablehnung gespeichert. Kein weiterer Empfänger verfügbar.');distribute()};
window.acceptPart=(kid,pid)=>{let k=db.kills.find(x=>x.id===kid),p=k.parts.find(x=>x.id===pid);if(!p||p.recipient!==user().id)return;p.accepted=true;p.source=(p.source||'Zuteilung')+' · angenommen';save();myShares()};
window.rejectPart=(kid,pid)=>{let k=db.kills.find(x=>x.id===kid),p=k.parts.find(x=>x.id===pid);if(!p||p.recipient!==user().id)return;p.rejectedBy=p.rejectedBy||[];if(!p.rejectedBy.includes(user().id))p.rejectedBy.push(user().id);p.recipient=null;p.accepted=false;p.source='abgelehnt – neu zu verteilen';save();myShares()};
const smallSpecies=['Ente','Fasan','Hase','Kaninchen','Taube'];
function driveCount(uid,species){let c=0,last=0;db.hunts.forEach(h=>(h.allocations||[]).forEach(a=>{if(a.recipient===uid&&a.species===species&&a.accepted!==false&&!String(a.source||'').startsWith('Schützenrecht')&&!String(a.source||'').startsWith('Direkt vom Schützen')){c++;last=Math.max(last,new Date(h.date).getTime())}}));return c*10+(last?last/1e15:0)}
function driveCandidate(h,a){let rejected=a.rejectedBy||[];let pool=h.participants.map(id=>db.users.find(u=>u.id===id)).filter(u=>u&&u.active&&!u.deleted&&!rejected.includes(u.id));if(!pool.length)return null;const currentCount=uid=>(h.allocations||[]).filter(x=>x!==a&&x.recipient===uid&&x.species===a.species&&!x.unusable&&!String(x.source||'').startsWith('Schützenrecht')&&!String(x.source||'').startsWith('Direkt vom Schützen')).length;return [...pool].sort((x,y)=>{let sx=driveCount(x.id,a.species)+currentCount(x.id)*10,sy=driveCount(y.id,a.species)+currentCount(y.id)*10;return sx-sy||String(x.name).localeCompare(String(y.name),'de')})[0]||null}
window.huntDistribution=(hid)=>{if(!canDistribute())return home();let h=db.hunts.find(x=>x.id===hid);if(!h)return drive();let rows=(h.allocations||[]).map((a,i)=>{let r=db.users.find(x=>x.id===a.recipient),sh=db.users.find(x=>x.id===a.shooter),regular=a.recipient&&!a.unusable&&!String(a.source||'').startsWith('Schützenrecht')&&!String(a.source||'').startsWith('Direkt vom Schützen'),pending=regular&&a.accepted===false;return `<div class='item'><b>${esc(a.species)} ${a.number||i+1}</b><div class='small'>Schütze: ${sh?esc(sh.name):'unbekannt'}</div><div class='small'>${a.unusable?'Nicht verwertbar':`Empfänger: <b>${r?esc(r.name):'offen'}</b>`}</div><div class='small'>${a.unusable?'aus Verteilung genommen':pending?'Vorschlag – noch nicht verteilt':a.recipient?'✓ verteilt':'offen'}${a.source?' · '+esc(a.source):''}</div>${pending?`<div class='row'><button class='btn compact' onclick='adminAcceptDrive(${h.id},${i})'>Verteilen</button><button class='btn secondary compact' onclick='adminRejectDrive(${h.id},${i})'>Ablehnen</button></div>`:''}${!a.unusable?`<button class='link' onclick='reassignDrive(${h.id},${i})'>Empfänger ändern</button>`:''}<button class='link danger' onclick='deleteDriveItem(${h.id},${i})'>Stück löschen</button></div>`}).join('');shell(`${head('Wild verteilen')}<div class='card'><h3>${esc(h.name)}</h3><div class='small'>${h.date} · ${(h.participants||[]).length} Teilnehmer</div></div><div class='card'><h3>Strecke & Verteilung</h3>${rows||'<div class="item">Für diese Jagd wurde keine Strecke eingetragen.</div>'}<button class='btn' onclick='confirmHunt(${h.id})'>Verteilung bestätigen</button><button class='btn secondary' onclick='shooterRights(${h.id})'>Schützen / Schützenrechte korrigieren</button><button class='btn secondary' onclick='window.print()'>Übersicht drucken / als PDF sichern</button><button class='btn secondary' onclick='drive()'>Zur Jagdübersicht</button><button class='btn secondary danger' onclick='deleteHunt(${h.id})'>Treibjagd vollständig löschen</button></div>`) };
window.reassignDrive=(hid,idx)=>{let h=db.hunts.find(x=>x.id===hid),a=h?.allocations?.[idx];if(!a||a.unusable)return;let names=h.participants.map(id=>db.users.find(u=>u.id===id)).filter(Boolean);let promptText='Empfänger auswählen:\n'+names.map((u,i)=>`${i+1}: ${u.name}`).join('\n');let n=prompt(promptText);let pick=names[Number(n)-1];if(!pick)return;a.recipient=pick.id;a.accepted=false;a.source='manueller Verteilungsvorschlag';save();confirmSaved('Empfänger wurde geändert.');huntDistribution(hid)};
window.confirmHunt=(hid)=>{let h=db.hunts.find(x=>x.id===hid);if(!h)return;h.distributionConfirmed=true;h.confirmedAt=new Date().toISOString();save();confirmSaved('Verteilung wurde gespeichert und bestätigt.');huntDistribution(hid)};
window.drive=()=>{if(!canDistribute())return myDrive();shell(`${head('Treibjagden')}<div class='card'><button class='btn bigplus' onclick='newDriveStep1()'>＋ Neue Treibjagd</button><div class='small' style='margin-top:8px'>Jagd anlegen → Anwesenheit → Strecke → Schützen & Mitnahmerecht → Verteilung.</div></div><div class='card'><h3>Letzte Jagden</h3>${db.hunts.slice().reverse().map(h=>`<div class='item' style='cursor:pointer'><div onclick='openDrive(${h.id})'><b>${h.date} · ${esc(h.name)}</b><div class='small'>${(h.participants||[]).length} anwesend · ${(h.allocations||[]).length} Stück Strecke</div><div class='small'>Status: ${h.stage==='attendance'?'Anwesenheit offen':h.stage==='bag'?'Strecke erfassen':h.stage==='shooter'?'Schützen erfassen':h.stage==='rights'?'Schützenrechte erfassen':h.distributionConfirmed?'abgeschlossen':'Verteilung'}</div></div><button class='link danger' onclick='event.stopPropagation();deleteHunt(${h.id})'>Löschen</button></div>`).join('')||'Noch keine Jagden.'}</div>`) };
window.newDriveStep1=()=>{shell(`${head('Neue Treibjagd')}<div class='card'><div class='step'>Schritt 1 · Jagd anlegen</div><label>Datum</label><input id='hd' type='date' value='${new Date().toISOString().slice(0,10)}'><label>Bezeichnung</label><input id='hn' placeholder='z. B. Treibjagd Markendorf'><button class='btn' onclick='createDriveBase()'>Weiter zur Anwesenheitsliste</button></div>`) };
window.createDriveBase=()=>{let h={id:Date.now(),date:hd.value,name:hn.value.trim()||'Treibjagd',participants:[],allocations:[],stage:'attendance'};db.hunts.push(h);save();confirmSaved('Treibjagd wurde angelegt. Jetzt Anwesenheit erfassen.');attendance(h.id)};
function sortBySurname(list){return [...list].sort((a,b)=>{const pa=String(a.name||'').trim().split(/\s+/),pb=String(b.name||'').trim().split(/\s+/),na=pa.pop()||'',nb=pb.pop()||'';return na.localeCompare(nb,'de',{sensitivity:'base'})||pa.join(' ').localeCompare(pb.join(' '),'de',{sensitivity:'base'})})}
window.attendance=hid=>{let h=db.hunts.find(x=>x.id===hid);if(!h)return drive();let attendancePeople=sortBySurname(hunters());shell(`${head('Anwesenheitsliste')}<div class='card'><div class='step'>Schritt 2 · Wer ist heute dabei?</div><h3>${esc(h.name)}</h3><div class='small'>${h.date} · alphabetisch nach Nachname</div>${db.groups.length?`<div class='sectiontitle'><b>Gruppen schnell auswählen</b></div><div class='filterbar'>${db.groups.map(g=>`<button class='chip' onclick='selectAttendanceGroup(${g.id})'>${esc(g.name)}</button>`).join('')}<button class='chip' onclick='selectAllAttendance()'>Alle</button></div>`:''}${attendancePeople.map(x=>`<label class='item attendanceperson'><input type='checkbox' class='participant' value='${x.id}' ${(h.participants||[]).includes(x.id)?'checked':''}> <span><b>${esc(x.name)}</b><div class='small'>${statusName(x)}${(x.groups||[]).length?' · '+(x.groups||[]).map(id=>db.groups.find(g=>g.id===id)?.name).filter(Boolean).join(', '):''}</div></span></label>`).join('')}<button class='btn secondary' onclick='quickGuest(${h.id})'>＋ Gast für diese Jagd anlegen</button><button class='btn' onclick='saveAttendance(${h.id})'>Anwesenheitsliste bestätigen</button></div>`) };
window.selectAttendanceGroup=id=>{let ids=new Set(db.users.filter(u=>u.active&&(u.groups||[]).includes(id)).map(u=>u.id));document.querySelectorAll('.participant').forEach(e=>{if(ids.has(+e.value))e.checked=true})};
window.selectAllAttendance=()=>document.querySelectorAll('.participant').forEach(e=>e.checked=true);
window.quickGuest=hid=>{let h=db.hunts.find(x=>x.id===hid);if(!h)return;let selected=[...document.querySelectorAll('.participant:checked')].map(x=>+x.value);h.participants=[...new Set([...(h.participants||[]),...selected])];let n=prompt('Name des Gastes:');if(!n?.trim())return;let id=Date.now();while(db.users.some(x=>x.id===id))id++;let u={id,name:n.trim(),status:'guest',fixedHunter:false,isHunter:true,isDistributor:false,isAdmin:false,active:true,temporary:true,groups:[]};db.users.push(u);h.participants=[...new Set([...h.participants,u.id])];save();confirmSaved('Gast wurde nur für diese Jagd hinzugefügt. Die bisherige Auswahl bleibt erhalten.');attendance(hid)};
window.saveAttendance=hid=>{let h=db.hunts.find(x=>x.id===hid);let ids=[...document.querySelectorAll('.participant:checked')].map(x=>+x.value);if(!ids.length)return alert('Mindestens eine anwesende Person auswählen.');h.participants=ids;h.stage='bag';save();confirmSaved('Anwesenheitsliste wurde gespeichert.');bagEntry(hid)};
window.bagEntry=hid=>{let h=db.hunts.find(x=>x.id===hid);if(!h)return drive();let counts={};(h.allocations||[]).forEach(a=>counts[a.species]=(counts[a.species]||0)+1);shell(`${head('Strecke erfassen')}<div class='card'><div class='step'>Schritt 3 · Strecke</div><h3>${esc(h.name)}</h3><div class='small'>${h.participants.length} Personen anwesend</div>${smallSpecies.map(sp=>`<div class='countrow'><b>${sp}</b><button onclick='changeCount("${sp}",-1)'>−</button><input class='bag' data-species='${sp}' type='number' min='0' value='${counts[sp]||0}'><button onclick='changeCount("${sp}",1)'>＋</button></div>`).join('')}<button class='btn' onclick='saveBag(${h.id})'>Weiter: Schützen zuordnen</button><button class='btn secondary' onclick='attendance(${h.id})'>Anwesenheit korrigieren</button></div>`) };
window.changeCount=(sp,d)=>{let e=[...document.querySelectorAll('.bag')].find(x=>x.dataset.species===sp);e.value=Math.max(0,(+e.value||0)+d)};
window.saveBag=hid=>{let h=db.hunts.find(x=>x.id===hid),items=[];document.querySelectorAll('.bag').forEach(e=>{for(let i=0;i<+e.value;i++)items.push(e.dataset.species)});h.allocations=[];let nums={};items.forEach(s=>{nums[s]=(nums[s]||0)+1;h.allocations.push({species:s,number:nums[s],shooter:null,recipient:null,source:'Schütze noch offen',accepted:false,rejectedBy:[],rightDecision:'release',unusable:false})});h.stage='shooter';save();confirmSaved('Strecke gespeichert. Jetzt wird je Schütze erfasst, wie viel Wild er geschossen hat.');shooterRights(h.id)};
function shooterBagCounts(h){let out={};(h.allocations||[]).forEach(a=>{if(a.shooter){out[a.shooter]=out[a.shooter]||{};let g=out[a.shooter][a.species]=out[a.shooter][a.species]||{shot:0,unusable:0};g.shot++;if(a.unusable)g.unusable++}});return out}
function speciesTotals(h){let t={};(h.allocations||[]).forEach(a=>t[a.species]=(t[a.species]||0)+1);return t}
function readShotState(){let out={};document.querySelectorAll('.shotCount').forEach(e=>{let k=e.dataset.uid+'|'+e.dataset.species;out[k]=out[k]||{};out[k].shot=Math.max(0,+e.value||0)});document.querySelectorAll('.unusableCount').forEach(e=>{let k=e.dataset.uid+'|'+e.dataset.species;out[k]=out[k]||{};out[k].unusable=Math.max(0,+e.value||0)});return out}
window.changeShooterCount=(uid,sp,d)=>{let e=document.querySelector(`.shotCount[data-uid="${uid}"][data-species="${sp}"]`);if(!e)return;let total=+document.querySelector(`[data-shot-total="${sp}"]`)?.dataset.total||0,others=[...document.querySelectorAll(`.shotCount[data-species="${sp}"]`)].filter(x=>x!==e).reduce((n,x)=>n+(+x.value||0),0),max=Math.max(0,total-others);e.value=Math.max(0,Math.min(max,(+e.value||0)+d));let bad=document.querySelector(`.unusableCount[data-uid="${uid}"][data-species="${sp}"]`);if(bad&&+bad.value>+e.value)bad.value=e.value;updateShotSummary()};
window.shotCountInput=(el)=>{let sp=el.dataset.species,total=+document.querySelector(`[data-shot-total="${sp}"]`)?.dataset.total||0,others=[...document.querySelectorAll(`.shotCount[data-species="${sp}"]`)].filter(x=>x!==el).reduce((n,x)=>n+(+x.value||0),0);el.value=Math.max(0,Math.min(Math.max(0,total-others),+el.value||0));let bad=document.querySelector(`.unusableCount[data-uid="${el.dataset.uid}"][data-species="${sp}"]`);if(bad&&+bad.value>+el.value)bad.value=el.value;updateShotSummary()};
window.changeUnusableCount=(uid,sp,d)=>{let e=document.querySelector(`.unusableCount[data-uid="${uid}"][data-species="${sp}"]`),shot=document.querySelector(`.shotCount[data-uid="${uid}"][data-species="${sp}"]`);if(!e||!shot)return;e.value=Math.max(0,Math.min(+shot.value||0,(+e.value||0)+d));e.dataset.touched='1';updateShotSummary()};
window.unusableCountInput=(el)=>{let shot=document.querySelector(`.shotCount[data-uid="${el.dataset.uid}"][data-species="${el.dataset.species}"]`);el.value=Math.max(0,Math.min(+shot?.value||0,+el.value||0));el.dataset.touched='1';updateShotSummary()};
function updateShotSummary(){document.querySelectorAll('[data-shot-total]').forEach(row=>{let sp=row.dataset.shotTotal,total=+row.dataset.total||0,assigned=[...document.querySelectorAll(`.shotCount[data-species="${sp}"]`)].reduce((n,x)=>n+(+x.value||0),0),bad=[...document.querySelectorAll(`.unusableCount[data-species="${sp}"]`)].reduce((n,x)=>n+(+x.value||0),0),open=Math.max(0,total-assigned),a=row.querySelector('.shot-assigned'),u=row.querySelector('.shot-unusable'),o=row.querySelector('.shot-open');if(a)a.textContent=assigned;if(u)u.textContent=bad;if(o)o.textContent=open+(open===0?' ✓':'')});document.querySelectorAll('.shotCount').forEach(e=>{let sp=e.dataset.species,total=+document.querySelector(`[data-shot-total="${sp}"]`)?.dataset.total||0,others=[...document.querySelectorAll(`.shotCount[data-species="${sp}"]`)].filter(x=>x!==e).reduce((n,x)=>n+(+x.value||0),0);e.max=Math.max(0,total-others)});document.querySelectorAll('.unusableCount').forEach(e=>{let shot=document.querySelector(`.shotCount[data-uid="${e.dataset.uid}"][data-species="${e.dataset.species}"]`);e.max=+shot?.value||0;if(+e.value>+e.max)e.value=e.max})}
window.shooterRights=hid=>{let h=db.hunts.find(x=>x.id===hid);if(!h)return drive();let people=sortBySurname(h.participants.map(id=>db.users.find(u=>u.id===id)).filter(Boolean)),counts=shooterBagCounts(h),totals=speciesTotals(h);shell(`${head('Strecke zuordnen')}<div class='card' style='position:sticky;top:0;z-index:20;box-shadow:0 2px 10px rgba(0,0,0,.12)'><div class='step'>Schritt 4 · Strecke im Blick</div><h3>Gesamtstrecke</h3>${smallSpecies.filter(sp=>totals[sp]).map(sp=>`<div class='item' data-shot-total='${sp}' data-total='${totals[sp]}'><b>${sp}</b><div class='small'>Gesamt: <b>${totals[sp]}</b> · zugeordnet: <b class='shot-assigned'>0</b> · nicht verwertbar: <b class='shot-unusable'>0</b> · noch offen: <b class='shot-open'>${totals[sp]}</b></div></div>`).join('')}</div><div class='card'><h3>Wer hat wie viel geschossen?</h3><div class='small'>Pro Schütze die Anzahl eintragen. „Davon nicht verwertbar“ gehört direkt zur geschossenen Menge. Die Gesamtstrecke zählt live herunter.</div></div>${people.map(u=>`<div class='card'><h3>${esc(u.name)}</h3>${smallSpecies.filter(sp=>totals[sp]).map(sp=>{let g=counts[u.id]?.[sp]||{shot:0,unusable:0};return `<div class='item'><b>${sp}</b><div class='small'>Geschossen</div><div class='countrow'><b>${sp}</b><button onclick='changeShooterCount(${u.id},"${sp}",-1)'>−</button><input class='shotCount' data-uid='${u.id}' data-species='${sp}' type='number' min='0' value='${g.shot}' oninput='shotCountInput(this)'><button onclick='changeShooterCount(${u.id},"${sp}",1)'>＋</button></div><div class='small'>Davon nicht verwertbar</div><div class='countrow'><b>nicht verwertbar</b><button onclick='changeUnusableCount(${u.id},"${sp}",-1)'>−</button><input class='unusableCount' data-uid='${u.id}' data-species='${sp}' data-touched='${g.shot?1:0}' type='number' min='0' value='${g.unusable}' oninput='unusableCountInput(this)'><button onclick='changeUnusableCount(${u.id},"${sp}",1)'>＋</button></div></div>`}).join('')}</div>`).join('')}<div class='card'><button class='btn' onclick='saveShooterBag(${h.id})'>Weiter: Schützenrechte</button><button class='btn secondary' onclick='bagEntry(${h.id})'>Strecke korrigieren</button></div>`);updateShotSummary()};
window.saveShooterBag=hid=>{let h=db.hunts.find(x=>x.id===hid);if(!h)return;let totals=speciesTotals(h),state=readShotState(),assigned={};for(const [k,v] of Object.entries(state)){let [uid,sp]=k.split('|');assigned[sp]=(assigned[sp]||0)+(v.shot||0);if((v.unusable||0)>(v.shot||0))return alert(`${sp}: Nicht verwertbar kann nicht größer als geschossen sein.`)}for(const sp of Object.keys(totals)){if((assigned[sp]||0)>totals[sp])return alert(`${sp}: Es wurden mehr Stück zugeordnet als auf der Strecke liegen.`);if((assigned[sp]||0)<totals[sp])return alert(`${sp}: Noch ${totals[sp]-(assigned[sp]||0)} Stück offen. Bitte einem Schützen zuordnen. Falls unbekannt, zuerst einen Jagdteilnehmer „Schütze unbekannt“ als Gast anlegen.`)}h.allocations.forEach(a=>{a.shooter=null;a.recipient=null;a.rightDecision='undecided';a.directRecipient=null;a.unusable=false;a.accepted=false;a.rejectedBy=[];a.source='Schützenrecht noch nicht entschieden'});for(const sp of Object.keys(totals)){let arr=h.allocations.filter(a=>a.species===sp),pos=0;for(const uid of h.participants){let v=state[uid+'|'+sp]||{shot:0,unusable:0};for(let j=0;j<(v.shot||0)&&pos<arr.length;j++,pos++){let a=arr[pos];a.shooter=+uid;a.unusable=j<(v.unusable||0);if(a.unusable){a.rightDecision='unusable';a.accepted=true;a.source='nicht verwertbar / nicht verteilt'}}}}h.stage='rights';save();confirmSaved('Strecke vollständig zugeordnet. Jetzt wird individuell entschieden, was die Schützen selbst behalten.');shooterDecisionSummary(hid)};
window.changeKeepCount=(uid,sp,d)=>{let e=document.querySelector(`.keepCount[data-uid="${uid}"][data-species="${sp}"]`);if(!e)return;let cur=e.value===''?0:+e.value||0;e.value=Math.max(0,Math.min(+e.max||0,cur+d));e.dataset.decided='1';updateRightsPool()};
window.keepCountInput=el=>{if(el.value===''){el.dataset.decided='0';return updateRightsPool()}el.value=Math.max(0,Math.min(+el.max||0,+el.value||0));el.dataset.decided='1';updateRightsPool()};
window.keepAll=(uid,sp,n)=>{let e=document.querySelector(`.keepCount[data-uid="${uid}"][data-species="${sp}"]`);if(e){e.value=n;e.dataset.decided='1';updateRightsPool()}};
window.releaseAll=(uid,sp)=>{let e=document.querySelector(`.keepCount[data-uid="${uid}"][data-species="${sp}"]`);if(e){e.value=0;e.dataset.decided='1';updateRightsPool()}};
function updateRightsPool(){let keep=0,release=0,open=0;document.querySelectorAll('.keepCount').forEach(e=>{let n=+e.max||0;if(e.dataset.decided!=='1'){open++;return}let k=+e.value||0;keep+=k;release+=n-k});let a=document.getElementById('rightsKeep'),b=document.getElementById('rightsRelease'),c=document.getElementById('rightsOpen');if(a)a.textContent=keep;if(b)b.textContent=release;if(c)c.textContent=open}
window.shooterDecisionSummary=hid=>{let h=db.hunts.find(x=>x.id===hid);if(!h)return drive();let groups={};h.allocations.forEach(a=>{if(!a.shooter||a.unusable)return;let k=a.shooter+'|'+a.species;groups[k]=groups[k]||{uid:a.shooter,sp:a.species,n:0,keep:0,decided:false};groups[k].n++;if(a.rightDecision==='keep'){groups[k].keep++;groups[k].decided=true}else if(a.rightDecision==='release')groups[k].decided=true});let rows=Object.values(groups);if(!rows.length){h.stage='distribution';save();return huntDistribution(hid)}shell(`${head('Schützenrecht')}<div class='card' style='position:sticky;top:0;z-index:20'><div class='step'>Schritt 5 · Individuelle Entscheidung</div><h3>Schützenrecht</h3><div class='small'>Keine Vorauswahl: Für jede Wildart muss entschieden werden, wie viel der Schütze selbst behält.</div><div class='small' style='margin-top:8px'>Selbst behalten: <b id='rightsKeep'>0</b> · Verteilungspool: <b id='rightsRelease'>0</b> · Entscheidungen offen: <b id='rightsOpen'>${rows.length}</b></div></div>${rows.map(g=>{let u=db.users.find(x=>x.id===g.uid);return `<div class='card'><h3>${esc(u?.name)} · ${esc(g.sp)}</h3><div class='small'>Verwertbar geschossen: <b>${g.n}</b></div><label>Davon selbst behalten</label><div class='countrow'><b>${g.sp}</b><button onclick='changeKeepCount(${g.uid},"${g.sp}",-1)'>−</button><input class='keepCount' data-uid='${g.uid}' data-species='${g.sp}' data-decided='${g.decided?1:0}' type='number' min='0' max='${g.n}' value='${g.decided?g.keep:''}' placeholder='–' oninput='keepCountInput(this)'><button onclick='changeKeepCount(${g.uid},"${g.sp}",1)'>＋</button></div><div class='row'><button class='btn secondary compact' onclick='releaseAll(${g.uid},"${g.sp}")'>Alles freigeben</button><button class='btn secondary compact' onclick='keepAll(${g.uid},"${g.sp}",${g.n})'>Alles selbst behalten</button></div></div>`}).join('')}<div class='card'><button class='btn' onclick='saveShooterDecisions(${h.id})'>Entscheidungen speichern & verteilen</button><button class='btn secondary' onclick='shooterRights(${h.id})'>Strecke korrigieren</button></div>`);updateRightsPool()};
window.saveShooterDecisions=hid=>{let h=db.hunts.find(x=>x.id===hid);if(!h)return;let wanted={};for(const e of document.querySelectorAll('.keepCount')){if(e.dataset.decided!=='1'||e.value==='')return alert('Bitte für jede Wildart entscheiden, wie viel der Schütze selbst behalten möchte. 0 ist erlaubt.');wanted[e.dataset.uid+'|'+e.dataset.species]=Math.max(0,Math.min(+e.max||0,+e.value||0))}let used={};h.allocations.forEach(a=>{a.recipient=null;a.rejectedBy=[];a.directRecipient=null;if(a.unusable){a.rightDecision='unusable';a.accepted=true;a.source='nicht verwertbar / nicht verteilt';return}a.accepted=false;let k=a.shooter+'|'+a.species;used[k]=used[k]||0;if(used[k]<(wanted[k]||0)){used[k]++;a.rightDecision='keep';a.recipient=a.shooter;a.accepted=true;a.source='Schützenrecht – eigenes Wild'}else{a.rightDecision='release';a.source='Vom Schützen freigegeben'}});h.allocations.forEach(a=>{if(a.rightDecision==='release'&&!a.unusable){let r=driveCandidate(h,a);a.recipient=r?.id||null;a.accepted=false;a.source=r?'Vom Schützen freigegeben – Verteilungsvorschlag':'Freigegeben – keine Person verfügbar'}});h.stage='distribution';h.distributionConfirmed=false;save();confirmSaved('Entscheidungen gespeichert. Nur verwertbares, freigegebenes Wild wurde in den Verteilungspool übernommen.');huntDistribution(hid)};
window.toggleDirect=i=>{let d=document.querySelector(`.driveDecision[data-i="${i}"]`),box=document.getElementById(`direct-${i}`);if(box)box.style.display=d?.value==='direct'?'block':'none'};
window.saveShooterRights=hid=>{let h=db.hunts.find(x=>x.id===hid);if(!h)return;for(let i=0;i<h.allocations.length;i++){let a=h.allocations[i],sh=+document.querySelector(`.driveShooter[data-i="${i}"]`)?.value||null,decision=document.querySelector(`.driveDecision[data-i="${i}"]`)?.value||'release',direct=+document.querySelector(`.driveDirect[data-i="${i}"]`)?.value||null;a.shooter=sh;a.rightDecision=decision;a.directRecipient=direct;a.rejectedBy=[];a.unusable=false;a.recipient=null;a.accepted=false;if(decision==='keep'){if(!sh)return alert(`${a.species} ${a.number}: Bitte zuerst einen Schützen auswählen oder das Stück freigeben.`);a.recipient=sh;a.accepted=true;a.source='Schützenrecht – eigenes Wild'}else if(decision==='direct'){if(!direct)return alert(`${a.species} ${a.number}: Bitte Empfänger für die direkte Weitergabe auswählen.`);a.recipient=direct;a.accepted=true;a.source='Direkt vom Schützen weitergegeben'}else if(decision==='unusable'){a.unusable=true;a.accepted=true;a.source='nicht verwertbar / nicht verteilt'}else{let r=driveCandidate(h,a);a.recipient=r?.id||null;a.accepted=false;a.source=r?'Freigegeben – Verteilungsvorschlag':'Freigegeben – keine Person verfügbar'}}h.stage='distribution';h.distributionConfirmed=false;save();confirmSaved('Schützenrechte gespeichert. Nur freigegebenes Wild wurde normal verteilt.');huntDistribution(hid)};
window.openDrive=hid=>{let h=db.hunts.find(x=>x.id===hid);if(!h)return drive();if(h.stage==='attendance')return attendance(hid);if(h.stage==='bag')return bagEntry(hid);if(h.stage==='shooter')return shooterRights(hid);if(h.stage==='rights')return shooterDecisionSummary(hid);huntDistribution(hid)};
window.myDrive=()=>{let u=user(), rows=[];db.hunts.forEach(h=>(h.allocations||[]).filter(a=>a.recipient===u.id).forEach(a=>rows.push(`${h.date} · ${a.species} · ${h.name}`)));shell(`${head('Meine Treibjagd-Zuteilungen')}<div class='card'>${rows.map(x=>`<div class='item'>${esc(x)}</div>`).join('')||'Keine Zuteilungen.'}</div>`)};
window.myShares=()=>{let u=user(),rows=[];db.kills.forEach(k=>k.parts.filter(p=>p.recipient===u.id).forEach(p=>rows.push({date:k.date,html:`<div class='item'><b>${k.date} · ${k.species} · ${esc(p.name)}</b><div class='small'>✓ Verteilt${p.source?' · '+esc(p.source):''}</div></div>`})));db.hunts.forEach(h=>(h.allocations||[]).filter(a=>a.recipient===u.id&&!a.unusable).forEach(a=>rows.push({date:h.date,html:`<div class='item'><b>${h.date} · ${a.species} · ${esc(h.name)}</b><div class='small'>✓ Verteilt${a.source?' · '+esc(a.source):''}</div></div>`})));shell(`${head('Meine Zuteilungen')}<div class='card'>${rows.length?rows.sort((a,b)=>b.date.localeCompare(a.date)).map(x=>x.html).join(''):'Noch keine Zuteilungen.'}</div>`)};
window.adminAcceptDrive=(hid,idx)=>{if(!canDistribute())return;let h=db.hunts.find(x=>x.id===hid),a=h?.allocations?.[idx];if(!a||!a.recipient||a.unusable)return;a.accepted=true;a.source=String(a.source||'Zuteilung').replace('Verteilungsvorschlag','verteilt').replace('neu vorgeschlagen','nach Ablehnung verteilt');save();confirmSaved('Stück ist verteilt.');huntDistribution(hid)};
window.adminRejectDrive=(hid,idx)=>{if(!canDistribute())return;let h=db.hunts.find(x=>x.id===hid),a=h?.allocations?.[idx];if(!a||!a.recipient||a.unusable||String(a.source||'').startsWith('Schützenrecht')||String(a.source||'').startsWith('Direkt vom Schützen'))return;a.rejectedBy=a.rejectedBy||[];if(!a.rejectedBy.includes(a.recipient))a.rejectedBy.push(a.recipient);let r=driveCandidate(h,a);a.recipient=r?.id||null;a.accepted=false;a.source=r?'nach Ablehnung neu vorgeschlagen':'abgelehnt – kein weiterer Empfänger verfügbar';save();confirmSaved(r?'Ablehnung gespeichert. Der nächste Empfänger wird vorgeschlagen.':'Ablehnung gespeichert. Kein weiterer Empfänger verfügbar.');huntDistribution(hid)};
window.deleteDriveItem=(hid,idx)=>{if(!isAdmin())return;let h=db.hunts.find(x=>x.id===hid),a=h?.allocations?.[idx];if(!a)return;if(!confirm(`${a.species} ${a.number||idx+1} wirklich löschen?`))return;h.allocations.splice(idx,1);let nums={};h.allocations.forEach(x=>{nums[x.species]=(nums[x.species]||0)+1;x.number=nums[x.species]});save();confirmSaved('Stück wurde gelöscht.');huntDistribution(hid)};
window.deleteHunt=hid=>{if(!isAdmin())return;let h=db.hunts.find(x=>x.id===hid);if(!h||!confirm(`Treibjagd „${h.name}“ einschließlich Strecke und Verteilung endgültig löschen?`))return;let tempIds=new Set((h.participants||[]).filter(id=>db.users.find(u=>u.id===id)?.temporary));db.hunts=db.hunts.filter(x=>x.id!==hid);db.users=db.users.filter(u=>!tempIds.has(u.id)||db.hunts.some(x=>(x.participants||[]).includes(u.id)));save();confirmSaved('Treibjagd wurde vollständig gelöscht.');drive()};
window.deleteKill=kid=>{if(!isAdmin())return;let k=db.kills.find(x=>x.id===kid);if(!k||!confirm(`${k.species} vom ${k.date} einschließlich aller Zuteilungen endgültig löschen?`))return;db.kills=db.kills.filter(x=>x.id!==kid);save();confirmSaved('Schalenwild wurde vollständig gelöscht.');distribute()};
window.deleteKillPart=(kid,pid)=>{if(!isAdmin())return;let k=db.kills.find(x=>x.id===kid),p=k?.parts?.find(x=>x.id===pid);if(!p||!confirm(`${p.name} aus diesem Stück löschen?`))return;k.parts=k.parts.filter(x=>x.id!==pid);if(!k.parts.length)db.kills=db.kills.filter(x=>x.id!==kid);save();confirmSaved('Teil wurde gelöscht.');distribute()};
window.deletePerson=id=>{if(!isAdmin())return;let u=db.users.find(x=>x.id===id);if(!u||u.mainAdmin)return alert('Der Admin kann nicht gelöscht werden.');let hasHistory=!canDeletePerson(id);let choice=hasHistory?prompt(`Für ${u.name} gibt es Historie.\n1 = Person aus Personenliste löschen, Historie behalten\n2 = Person UND alle zugehörigen Jagd-/Verteilungsdaten löschen\nABBRECHEN = nichts ändern`):'2';if(choice!=='1'&&choice!=='2')return;if(!confirm(`${u.name} wirklich löschen?`))return;if(choice==='1'){u.active=false;u.deleted=true}else{db.kills=db.kills.filter(k=>k.shooter!==id).map(k=>({...k,parts:(k.parts||[]).filter(p=>p.recipient!==id)})).filter(k=>k.parts.length);db.hunts.forEach(h=>{h.participants=(h.participants||[]).filter(x=>x!==id);h.allocations=(h.allocations||[]).filter(a=>a.shooter!==id&&a.recipient!==id&&a.directRecipient!==id)});db.users=db.users.filter(x=>x.id!==id)}save();confirmSaved(choice==='1'?'Person wurde aus der Personenliste entfernt; Historie bleibt erhalten.':'Person und zugehörige Daten wurden gelöscht.');hunterAdmin()};
window.historyView=()=>{if(!canDistribute())return home();shell(`${head('Historie')}<div class='card'><h3>Schalenwild</h3>${db.kills.slice().reverse().map(k=>`<div class='item'><b>${k.date} · ${k.species}</b><div class='small'>${k.parts.map(p=>`${esc(p.name)}: ${p.recipient?esc(db.users.find(u=>u.id===p.recipient)?.name):'offen'}${p.source?' ('+p.source+')':''}`).join(' · ')}</div></div>`).join('')||'Noch keine Einträge.'}</div><div class='card'><h3>Treibjagden</h3>${db.hunts.slice().reverse().map(h=>`<div class='item'><b>${h.date} · ${esc(h.name)}</b><div class='small'>${(h.allocations||[]).map(a=>`${a.species}: ${esc(db.users.find(u=>u.id===a.recipient)?.name)}`).join(' · ')}</div></div>`).join('')||'Noch keine Einträge.'}</div>`)};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=0153').catch(()=>{});
(async()=>{const {data}=await sb.auth.getSession();if(!data.session)return login();authUser=data.session.user;try{await loadCloudState();if(!bindSessionPerson()){await sb.auth.signOut();authUser=null;return login()}home()}catch(e){console.error(e);login();alert('Zentrale Datenbank noch nicht bereit: '+e.message)}})();
