const KEY='wildverteilung_v2';
const old=JSON.parse(localStorage.getItem('wildverteilung_v1')||'null');
const seed={users:[{id:1,name:'Administrator',login:'admin',pin:'1234',role:'admin',phone:'',active:true},{id:2,name:'Uwe',login:'uwe',pin:'1111',role:'hunter',phone:'',active:true},{id:3,name:'Jürgen',login:'juergen',pin:'2222',role:'hunter',phone:'',active:true}],kills:[],hunts:[],session:null};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||old||seed; db.hunts=db.hunts||[]; db.users.forEach(u=>u.active=u.active!==false);
const save=()=>localStorage.setItem(KEY,JSON.stringify(db)), A=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shell(x){A.innerHTML=`<div class='wrap'>${x}</div>`} function user(){return db.users.find(x=>x.id===db.session)} function hunters(){return db.users.filter(x=>x.role==='hunter'&&x.active)}
function login(){shell(`<div class='brand'><div class='mark'>🦌</div><h1>Wildverteilung</h1><div class='small'>Jagdgemeinschaft</div></div><div class='card'><label>Benutzername</label><input id='l' autocomplete='username'><label>PIN</label><input id='p' type='password' inputmode='numeric'><button class='btn' id='go'>Anmelden</button><button class='link' id='forgot'>PIN vergessen – SMS-Code</button></div><p class='small' style='text-align:center'>Demo-Admin: admin / 1234</p>`);go.onclick=()=>{let u=db.users.find(x=>x.active&&x.login.toLowerCase()===l.value.trim().toLowerCase()&&x.pin===p.value);if(!u)return alert('Benutzername oder PIN nicht korrekt.');db.session=u.id;save();home()};forgot.onclick=()=>alert('Der Ablauf ist eingebaut. Für echte SMS braucht die Online-Version noch Server + SMS-Anbieter.')} 
function head(title){return `<div class='top'><button onclick='home()'>‹</button><h2>${title}</h2><button onclick='logout()'>⎋</button></div>`} window.logout=()=>{db.session=null;save();login()};
function home(){let u=user();if(!u)return login();shell(`<div class='top'><div><div class='small'>Angemeldet als</div><h2 style='margin:2px 0'>${esc(u.name)}</h2></div><button onclick='logout()'>⎋</button></div><div class='grid'><button class='tile' onclick='myShares()'><span>🥩</span>Meine Zuteilungen</button><button class='tile secondary' onclick='newKill()'><span>🦌</span>Schalenwild</button><button class='tile secondary' onclick='drive()'><span>🌿</span>Treibjagd</button>${u.role==='admin'?`<button class='tile' onclick='distribute()'><span>⚖️</span>Offene Verteilung</button><button class='tile' onclick='hunterAdmin()'><span>👥</span>Jäger</button><button class='tile secondary' onclick='historyView()'><span>📜</span>Historie</button>`:''}</div>`)} window.home=home;
window.newKill=()=>{shell(`${head('Schalenwild eintragen')}<div class='card'><label>Datum</label><input id='date' type='date' value='${new Date().toISOString().slice(0,10)}'><label>Wildart</label><select id='species'><option>Damwild</option><option>Schwarzwild</option></select><label>Schütze</label><select id='shooter'>${hunters().map(x=>`<option value='${x.id}'>${esc(x.name)}</option>`)}</select><label>Verwertbare Teile</label><div id='checks'>${['Keule links','Keule rechts','Rücken','Vorderviertel links','Vorderviertel rechts'].map((x,i)=>`<label class='item'><input type='checkbox' class='part' value='${x}' ${i<5?'checked':''}> ${x}</label>`).join('')}</div><label>Bemerkung</label><input id='note'><button class='btn' id='savekill'>Stück speichern</button></div>`);savekill.onclick=()=>{let ps=[...document.querySelectorAll('.part:checked')].map((e,i)=>({id:i,name:e.value,recipient:null,source:'open'}));if(!ps.length)return alert('Mindestens einen verwertbaren Teil auswählen.');db.kills.push({id:Date.now(),date:date.value,species:species.value,shooter:+shooter.value,parts:ps,note:note.value,createdBy:user().id});save();alert('Gespeichert. Der Schütze kann jetzt zuerst auswählen.');distribute()}}
window.hunterAdmin=()=>{shell(`${head('Jägerverwaltung')}<div class='card'><h3>Jäger anlegen</h3><input id='n' placeholder='Name'><input id='lo' placeholder='Benutzername' style='margin-top:8px'><input id='ph' placeholder='Mobilnummer für SMS' type='tel' style='margin-top:8px'><input id='pi' placeholder='PIN (4–6 Ziffern)' inputmode='numeric' style='margin-top:8px'><button class='btn' id='add'>Jäger hinzufügen</button></div><div class='card'><h3>Namensliste</h3>${db.users.map(u=>`<div class='item'><b>${esc(u.name)}</b> <span class='pill'>${u.role==='admin'?'Admin':'Jäger'}</span><div class='small'>${esc(u.login)}${u.phone?' · '+esc(u.phone):''}${u.active?'':' · inaktiv'}</div>${u.role==='hunter'?`<button class='link' onclick='toggleHunter(${u.id})'>${u.active?'Deaktivieren':'Aktivieren'}</button>`:''}</div>`).join('')}</div>`);add.onclick=()=>{if(!n.value||!lo.value||!/^[0-9]{4,6}$/.test(pi.value))return alert('Name, Benutzername und PIN mit 4–6 Ziffern eingeben.');if(db.users.some(u=>u.login.toLowerCase()===lo.value.trim().toLowerCase()))return alert('Benutzername bereits vergeben.');db.users.push({id:Date.now(),name:n.value.trim(),login:lo.value.trim(),pin:pi.value,phone:ph.value.trim(),role:'hunter',active:true});save();hunterAdmin()}}; window.toggleHunter=id=>{let u=db.users.find(x=>x.id===id);u.active=!u.active;save();hunterAdmin()};
function partBase(n){return n.startsWith('Keule')?'Keule':n.startsWith('Vorderviertel')?'Vorderviertel':n}
function score(uid,name,species){let total=0,same=0,kind=0,last=0;db.kills.forEach(k=>k.parts.forEach(p=>{if(p.recipient===uid){total++;if(k.species===species)same++;if(partBase(p.name)===partBase(name))kind++;last=Math.max(last,new Date(k.date).getTime())}}));return kind*8+same*2+total+(last?last/1e15:0)}
function shooterPickHtml(k){let shooter=db.users.find(u=>u.id===k.shooter), open=k.parts.filter(p=>!p.recipient);return `<div class='card'><b>${k.species}</b> · ${k.date}<div class='small'>Schütze: ${esc(shooter?.name)}</div><h3>1. Schütze wählt zuerst</h3>${open.map(p=>`<button class='btn secondary' onclick='pickShooter(${k.id},${p.id})'>${esc(p.name)} an ${esc(shooter?.name)}</button>`).join('')}<button class='link' onclick='shooterWaive(${k.id})'>Schütze verzichtet auf einen Teil</button><button class='link' onclick='takeWhole(${k.id})'>Schütze übernimmt das ganze Stück</button></div>`}
window.distribute=()=>{let open=db.kills.filter(k=>k.parts.some(p=>!p.recipient));shell(`${head('Offene Verteilung')}${open.length?'':`<div class='card'>Keine offenen Stücke.</div>`}${open.map(k=>{if(!k.shooterDecision)return shooterPickHtml(k);return `<div class='card'><b>${k.species}</b> · ${k.date}<div class='small'>Schütze: ${esc(db.users.find(u=>u.id===k.shooter)?.name)}</div>${k.parts.map(p=>`<div class='item'>${esc(p.name)}: <b>${p.recipient?esc(db.users.find(u=>u.id===p.recipient)?.name):'offen'}</b></div>`).join('')}<button class='btn' onclick='auto(${k.id})'>Rest fair verteilen</button></div>`}).join('')}`)};
window.pickShooter=(kid,pid)=>{let k=db.kills.find(x=>x.id===kid),p=k.parts.find(x=>x.id===pid);p.recipient=k.shooter;p.source='Schützenwahl';k.shooterDecision='part';save();distribute()}; window.shooterWaive=kid=>{db.kills.find(x=>x.id===kid).shooterDecision='waive';save();distribute()}; window.takeWhole=kid=>{let k=db.kills.find(x=>x.id===kid);k.parts.forEach(p=>{p.recipient=k.shooter;p.source='Schütze ganzes Stück'});k.shooterDecision='whole';save();distribute()};
window.auto=id=>{let k=db.kills.find(x=>x.id===id), hs=hunters();k.parts.forEach(p=>{if(p.recipient)return;let ranked=[...hs].sort((a,b)=>score(a.id,p.name,k.species)-score(b.id,p.name,k.species));p.recipient=ranked[0]?.id;p.source='Automatik'});save();distribute()};
const smallSpecies=['Ente','Fasan','Hase','Kaninchen','Taube'];
function driveCount(uid,species){let c=0,last=0;db.hunts.forEach(h=>(h.allocations||[]).forEach(a=>{if(a.recipient===uid&&a.species===species){c++;last=Math.max(last,new Date(h.date).getTime())}}));return c*10+(last?last/1e15:0)}
window.drive=()=>{let u=user(); if(u.role!=='admin')return myDrive();shell(`${head('Treibjagd')}<div class='card'><h3>Neue Jagd</h3><label>Datum</label><input id='hd' type='date' value='${new Date().toISOString().slice(0,10)}'><label>Bezeichnung</label><input id='hn' placeholder='z. B. Entenjagd Markendorf'><h3>Teilnehmer</h3>${hunters().map(x=>`<label class='item'><input type='checkbox' class='participant' value='${x.id}' checked> ${esc(x.name)}</label>`).join('')}<h3>Strecke</h3>${smallSpecies.map(s=>`<label>${s}</label><input class='bag' data-species='${s}' type='number' min='0' value='0'>`).join('')}<button class='btn' id='createhunt'>Jagd anlegen & verteilen</button></div><div class='card'><h3>Letzte Jagden</h3>${db.hunts.slice().reverse().map(h=>`<div class='item'><b>${h.date} · ${esc(h.name)}</b><div class='small'>${(h.allocations||[]).map(a=>`${a.species}: ${esc(db.users.find(x=>x.id===a.recipient)?.name)}`).join(' · ')}</div></div>`).join('')||'Noch keine Jagden.'}</div>`);createhunt.onclick=()=>{let participants=[...document.querySelectorAll('.participant:checked')].map(x=>+x.value);if(!participants.length)return alert('Mindestens einen Teilnehmer auswählen.');let items=[];document.querySelectorAll('.bag').forEach(e=>{for(let i=0;i<+e.value;i++)items.push(e.dataset.species)});let h={id:Date.now(),date:hd.value,name:hn.value||'Treibjagd',participants,allocations:[]};items.forEach(s=>{let ranked=participants.map(id=>db.users.find(u=>u.id===id)).sort((a,b)=>driveCount(a.id,s)-driveCount(b.id,s));let r=ranked[0];h.allocations.push({species:s,recipient:r.id,source:'Mitnahme-Automatik'})});db.hunts.push(h);save();drive()}}
window.myDrive=()=>{let u=user(), rows=[];db.hunts.forEach(h=>(h.allocations||[]).filter(a=>a.recipient===u.id).forEach(a=>rows.push(`${h.date} · ${a.species} · ${h.name}`)));shell(`${head('Meine Treibjagd-Zuteilungen')}<div class='card'>${rows.map(x=>`<div class='item'>${esc(x)}</div>`).join('')||'Keine Zuteilungen.'}</div>`)};
window.myShares=()=>{let u=user(),rows=[];db.kills.forEach(k=>k.parts.filter(p=>p.recipient===u.id).forEach(p=>rows.push(`${k.date} · ${k.species} · ${p.name}`)));db.hunts.forEach(h=>(h.allocations||[]).filter(a=>a.recipient===u.id).forEach(a=>rows.push(`${h.date} · ${a.species} · Treibjagd`)));shell(`${head('Meine Zuteilungen')}<div class='card'>${rows.length?rows.sort().reverse().map(x=>`<div class='item'>${esc(x)}</div>`).join(''):'Noch keine Zuteilungen.'}</div>`)};
window.historyView=()=>shell(`${head('Historie')}<div class='card'><h3>Schalenwild</h3>${db.kills.slice().reverse().map(k=>`<div class='item'><b>${k.date} · ${k.species}</b><div class='small'>${k.parts.map(p=>`${esc(p.name)}: ${p.recipient?esc(db.users.find(u=>u.id===p.recipient)?.name):'offen'}${p.source?' ('+p.source+')':''}`).join(' · ')}</div></div>`).join('')||'Noch keine Einträge.'}</div><div class='card'><h3>Treibjagden</h3>${db.hunts.slice().reverse().map(h=>`<div class='item'><b>${h.date} · ${esc(h.name)}</b><div class='small'>${(h.allocations||[]).map(a=>`${a.species}: ${esc(db.users.find(u=>u.id===a.recipient)?.name)}`).join(' · ')}</div></div>`).join('')||'Noch keine Einträge.'}</div>`);
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{}); db.session?home():login();
